# Generated by Django 5.2.8 on 2025-11-27 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('kyc_submit', 'KYC Submitted'), ('kyc_approve', 'KYC Approved'), ('kyc_reject', 'KYC Rejected'), ('document_upload', 'Document Uploaded'), ('document_delete', 'Document Deleted'), ('profile_update', 'Profile Updated'), ('login', 'User Login'), ('logout', 'User Logout'), ('password_change', 'Password Changed'), ('other', 'Other Action')], max_length=50)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'indexes': [models.Index(fields=['user', 'action'], name='audit_logs_user_id_d685f3_idx'), models.Index(fields=['created_at'], name='audit_logs_created_262184_idx')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('bank', 'Bank Proof'), ('address', 'Address Proof'), ('photo', 'Photograph'), ('signature', 'Signature'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='Size in bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'indexes': [models.Index(fields=['user', 'document_type'], name='documents_user_id_588d9f_idx')],
            },
        ),
        migrations.CreateModel(
            name='KYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('aadhaar_name', models.CharField(blank=True, max_length=200, null=True)),
                ('aadhaar_dob', models.DateField(blank=True, null=True)),
                ('aadhaar_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('aadhaar_address', models.TextField(blank=True, null=True)),
                ('aadhaar_verified', models.BooleanField(default=False)),
                ('aadhaar_verified_at', models.DateTimeField(blank=True, null=True)),
                ('aadhaar_front', models.FileField(blank=True, null=True, upload_to='kyc/aadhaar/')),
                ('aadhaar_back', models.FileField(blank=True, null=True, upload_to='kyc/aadhaar/')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('pan_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pan_father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('pan_dob', models.DateField(blank=True, null=True)),
                ('pan_verified', models.BooleanField(default=False)),
                ('pan_verified_at', models.DateTimeField(blank=True, null=True)),
                ('pan_aadhaar_linked', models.BooleanField(default=False)),
                ('pan_document', models.FileField(blank=True, null=True, upload_to='kyc/pan/')),
                ('bank_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=11, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=200, null=True)),
                ('account_type', models.CharField(blank=True, max_length=20, null=True)),
                ('bank_verified', models.BooleanField(default=False)),
                ('bank_verified_at', models.DateTimeField(blank=True, null=True)),
                ('bank_proof', models.FileField(blank=True, null=True, upload_to='kyc/bank/')),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True)),
                ('address_proof', models.FileField(blank=True, null=True, upload_to='kyc/address/')),
                ('aadhaar_api_response', models.JSONField(blank=True, null=True)),
                ('pan_api_response', models.JSONField(blank=True, null=True)),
                ('bank_api_response', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kycs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC',
                'verbose_name_plural': 'KYCs',
                'db_table': 'kyc',
                'indexes': [models.Index(fields=['status', 'created_at'], name='kyc_status_8246f8_idx'), models.Index(fields=['aadhaar_number'], name='kyc_aadhaar_48a241_idx'), models.Index(fields=['pan_number'], name='kyc_pan_num_4cb1af_idx')],
            },
        ),
    ]
