# Generated by Django 5.2.8 on 2025-11-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='aadhaar_last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='aadhaar_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kyc',
            name='pan_last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='pan_retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
