# Generated by Django 5.2.8 on 2025-12-01 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_kyc_aadhaar_last_retry_at_kyc_aadhaar_retry_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='dob_validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='kyc',
            name='name_match_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Name similarity score (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='kyc',
            name='name_validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('passed', 'Passed'), ('failed', 'Failed'), ('needs_review', 'Needs Manual Review')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='kyc',
            name='validation_errors',
            field=models.JSONField(blank=True, default=dict, help_text='Stores validation error details'),
        ),
    ]
