# Generated by Django 4.2.29 on 2026-03-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0004_aadhaar_session_pan_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaarsession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
