# Generated by Django 5.2.8 on 2025-12-05 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
        ('partners', '0002_cpdocument_cpinvite_cplead_cppropertyauthorization_and_more'),
        ('properties', '0005_alter_property_property_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='referral_code_used',
            field=models.CharField(blank=True, help_text='CP referral code entered by customer at investment time (overrides referred_by_cp)', max_length=50),
        ),
        migrations.AlterField(
            model_name='investment',
            name='referred_by_cp',
            field=models.ForeignKey(blank=True, help_text='CP who originally brought this customer (via CPCustomerRelation)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_investments', to='partners.channelpartner'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['referral_code_used'], name='investments_referra_3c91dc_idx'),
        ),
    ]
