# Generated by Django 5.2.8 on 2025-12-10 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_investment_referral_code_used_and_more'),
        ('partners', '0003_cpinvite_is_permanent'),
        ('properties', '0005_alter_property_property_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for cheque', max_length=150),
        ),
        migrations.AddField(
            model_name='investment',
            name='branch_name',
            field=models.CharField(blank=True, help_text='Bank branch name', max_length=150),
        ),
        migrations.AddField(
            model_name='investment',
            name='cheque_date',
            field=models.DateField(blank=True, help_text='Cheque date', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='cheque_image',
            field=models.ImageField(blank=True, help_text='Scanned cheque image', null=True, upload_to='investments/cheques/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='investment',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque/Draft number', max_length=50),
        ),
        migrations.AddField(
            model_name='investment',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='Bank IFSC code', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='neft_rtgs_ref_no',
            field=models.CharField(blank=True, help_text='NEFT / RTGS reference number', max_length=100),
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_approved_at',
            field=models.DateTimeField(blank=True, help_text='When payment was approved by admin', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_approved_investments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_date',
            field=models.DateTimeField(blank=True, help_text='When payment was made by customer', null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ONLINE', 'Online'), ('POS', 'POS'), ('DRAFT_CHEQUE', 'Draft / Cheque'), ('NEFT_RTGS', 'NEFT / RTGS')], help_text='Payment method used by customer', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_mode',
            field=models.CharField(blank=True, help_text='For ONLINE/POS: UPI, Card, NetBanking, Wallet, etc.', max_length=50),
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_notes',
            field=models.TextField(blank=True, help_text='Customer notes about payment'),
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for payment rejection'),
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', help_text='Payment verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='investment',
            name='pos_slip_image',
            field=models.ImageField(blank=True, help_text='Image of POS charge slip', null=True, upload_to='investments/pos_slips/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='investment',
            name='transaction_no',
            field=models.CharField(blank=True, help_text='Payment gateway transaction ID / POS transaction no.', max_length=100),
        ),
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment Approval'), ('payment_approved', 'Payment Approved'), ('payment_rejected', 'Payment Rejected'), ('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('active', 'Active'), ('completed', 'Completed'), ('redeemed', 'Redeemed'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending_payment', max_length=20),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['payment_method'], name='investments_payment_3c4ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['payment_status'], name='investments_payment_71d6f6_idx'),
        ),
    ]
