# Generated by Django 5.2.8 on 2025-12-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investment_bank_name_investment_branch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for cheque', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='branch_name',
            field=models.CharField(blank=True, help_text='Bank branch name', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='cheque_number',
            field=models.CharField(blank=True, help_text='Cheque/Draft number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='ifsc_code',
            field=models.CharField(blank=True, help_text='Bank IFSC code', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='neft_rtgs_ref_no',
            field=models.CharField(blank=True, help_text='NEFT / RTGS reference number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='transaction_no',
            field=models.CharField(blank=True, help_text='Payment gateway transaction ID / POS transaction no.', max_length=100, null=True),
        ),
    ]
