# Generated by Django 5.2.8 on 2025-12-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_investment_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Remaining amount to be paid', max_digits=15),
        ),
        migrations.AddField(
            model_name='investment',
            name='is_partial_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='minimum_required_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total investment amount (full price)', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='payment_due_date',
            field=models.DateField(blank=True, help_text='Due date for remaining payment', null=True),
        ),
    ]
