# Generated by Django 5.2.8 on 2025-11-26 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('partners', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cpcommissionrule',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AddField(
            model_name='cpcustomerrelation',
            name='cp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='partners.channelpartner'),
        ),
        migrations.AddField(
            model_name='cpcustomerrelation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_cp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cpcustomerrelation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_customer_relations', to='accounts.organization'),
        ),
        migrations.AddIndex(
            model_name='channelpartner',
            index=models.Index(fields=['organization', 'is_active'], name='channel_par_organiz_c8fb25_idx'),
        ),
        migrations.AddIndex(
            model_name='channelpartner',
            index=models.Index(fields=['parent_cp'], name='channel_par_parent__acff2d_idx'),
        ),
        migrations.AddIndex(
            model_name='channelpartner',
            index=models.Index(fields=['cp_code'], name='channel_par_cp_code_e3930a_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['organization', 'is_active'], name='commission__organiz_b32ed9_idx'),
        ),
        migrations.AddIndex(
            model_name='cpcustomerrelation',
            index=models.Index(fields=['cp', 'is_active'], name='cp_customer_cp_id_b49768_idx'),
        ),
        migrations.AddIndex(
            model_name='cpcustomerrelation',
            index=models.Index(fields=['customer'], name='cp_customer_custome_0e5c30_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cpcustomerrelation',
            unique_together={('cp', 'customer', 'organization')},
        ),
    ]
