# Generated by Django 5.2.8 on 2025-12-05 19:07

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('properties', '0005_alter_property_property_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CPDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('pan_card', 'PAN Card'), ('rera_certificate', 'RERA Certificate'), ('gst_certificate', 'GST Certificate'), ('business_license', 'Business License'), ('bank_proof', 'Bank Account Proof'), ('address_proof', 'Address Proof'), ('id_proof', 'ID Proof'), ('agreement', 'Agreement'), ('other', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, help_text='Description of document')),
                ('file', models.FileField(help_text='Upload document file', upload_to='cp_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When was document verified?', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
            ],
            options={
                'verbose_name': 'CP Document',
                'verbose_name_plural': 'CP Documents',
                'db_table': 'cp_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CPInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invite_code', models.CharField(help_text='Unique invite code (auto-generated)', max_length=50, unique=True)),
                ('phone', models.CharField(help_text='Phone number invited', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Email invited (optional)', max_length=254)),
                ('name', models.CharField(blank=True, help_text='Name of person invited (optional)', max_length=255)),
                ('is_used', models.BooleanField(default=False, help_text='Has invite been used?')),
                ('used_at', models.DateTimeField(blank=True, help_text='When was invite used?', null=True)),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Invite expires after this date', null=True)),
                ('is_expired', models.BooleanField(default=False, help_text='Has invite expired?')),
                ('message', models.TextField(blank=True, help_text='Personalized message from CP to invitee')),
            ],
            options={
                'verbose_name': 'CP Invite',
                'verbose_name_plural': 'CP Invites',
                'db_table': 'cp_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CPLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(help_text='Name of potential customer', max_length=255)),
                ('phone', models.CharField(help_text='Phone number of lead', max_length=15)),
                ('email', models.EmailField(blank=True, help_text='Email of lead (optional)', max_length=254)),
                ('lead_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('site_visit_scheduled', 'Site Visit Scheduled'), ('site_visit_done', 'Site Visit Done'), ('negotiation', 'Negotiation'), ('converted', 'Converted'), ('lost', 'Lost'), ('not_interested', 'Not Interested')], default='new', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='CP notes about this lead')),
                ('next_follow_up_date', models.DateField(blank=True, help_text='When to follow up next?', null=True)),
                ('converted_at', models.DateTimeField(blank=True, help_text='When did lead convert to customer?', null=True)),
                ('lead_source', models.CharField(blank=True, help_text='Where did this lead come from? (Facebook, WhatsApp, etc.)', max_length=50)),
            ],
            options={
                'verbose_name': 'CP Lead',
                'verbose_name_plural': 'CP Leads',
                'db_table': 'cp_leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CPPropertyAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_authorized', models.BooleanField(default=True, help_text='Is CP authorized to sell this property?')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='approved', max_length=20)),
                ('referral_link', models.CharField(blank=True, help_text='Unique referral link for this CP + Property combination', max_length=500)),
                ('custom_brochure', models.FileField(blank=True, help_text='Custom brochure for this CP (optional)', null=True, upload_to='cp_brochures/')),
                ('authorized_at', models.DateTimeField(auto_now_add=True, help_text='When was authorization granted?')),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this authorization')),
            ],
            options={
                'verbose_name': 'CP Property Authorization',
                'verbose_name_plural': 'CP Property Authorizations',
                'db_table': 'cp_property_authorizations',
                'ordering': ['-authorized_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='channelpartner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Channel Partner', 'verbose_name_plural': 'Channel Partners'},
        ),
        migrations.AlterModelOptions(
            name='commissionrule',
            options={'ordering': ['-created_at'], 'verbose_name': 'Commission Rule', 'verbose_name_plural': 'Commission Rules'},
        ),
        migrations.AlterModelOptions(
            name='cpcommissionrule',
            options={'verbose_name': 'CP Commission Rule', 'verbose_name_plural': 'CP Commission Rules'},
        ),
        migrations.AlterModelOptions(
            name='cpcustomerrelation',
            options={'ordering': ['-referral_date'], 'verbose_name': 'CP-Customer Relation', 'verbose_name_plural': 'CP-Customer Relations'},
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='agent_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('company', 'Company'), ('franchise', 'Franchise')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='annual_revenue_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Annual revenue target (USD or INR)', max_digits=15),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='business_address',
            field=models.TextField(blank=True, help_text='Business/Office address (separate from personal)'),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='commission_notes',
            field=models.TextField(blank=True, help_text="Custom commission terms, notes (e.g., '5% on first 50L, 7% thereafter')"),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this CP record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='dedicated_support_contact',
            field=models.CharField(blank=True, help_text='Dedicated support person name/phone for this CP', max_length=255),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this CP record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_cps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='last_modified_date',
            field=models.DateTimeField(auto_now=True, help_text='Last modification timestamp'),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='onboarding_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', help_text='Current onboarding status', max_length=20),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='partner_tier',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', help_text='Partner tier based on performance', max_length=20),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='program_end_date',
            field=models.DateField(blank=True, help_text='Date when CP program ends (null = ongoing)', null=True),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='program_start_date',
            field=models.DateField(blank=True, help_text='Date when CP program started', null=True),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='q1_performance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q1 (Jan-Mar) performance', max_digits=15),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='q2_performance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q2 (Apr-Jun) performance', max_digits=15),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='q3_performance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q3 (Jul-Sep) performance', max_digits=15),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='q4_performance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Q4 (Oct-Dec) performance', max_digits=15),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='regulatory_compliance_approved',
            field=models.BooleanField(default=False, help_text='Has regulatory compliance been approved by admin?'),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='rera_number',
            field=models.CharField(blank=True, help_text='RERA Registration Number (Required for real estate)', max_length=50),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='source',
            field=models.CharField(choices=[('direct', 'Direct'), ('referral', 'Referral'), ('website', 'Website'), ('advertisement', 'Advertisement'), ('event', 'Event'), ('other', 'Other')], default='direct', help_text='How did this CP come to us?', max_length=20),
        ),
        migrations.AddField(
            model_name='channelpartner',
            name='technical_setup_notes',
            field=models.TextField(blank=True, help_text='Technical setup notes, onboarding instructions'),
        ),
        migrations.AddField(
            model_name='cpcommissionrule',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Admin who assigned this rule', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_commission_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cpcommissionrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cpcommissionrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cpcustomerrelation',
            name='expiry_date',
            field=models.DateTimeField(blank=True, help_text='Date when this relationship expires', null=True),
        ),
        migrations.AddField(
            model_name='cpcustomerrelation',
            name='is_expired',
            field=models.BooleanField(default=False, help_text='Has this relationship expired?'),
        ),
        migrations.AddField(
            model_name='cpcustomerrelation',
            name='validity_days',
            field=models.IntegerField(default=90, help_text='Number of days this relationship is valid'),
        ),
        migrations.AlterField(
            model_name='channelpartner',
            name='cp_code',
            field=models.CharField(help_text='Auto-generated unique CP code (e.g., CP001234)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='channelpartner',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST Number (GSTIN)', max_length=15),
        ),
        migrations.AlterField(
            model_name='channelpartner',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is CP active and can operate?'),
        ),
        migrations.AlterField(
            model_name='channelpartner',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Has admin verified and approved this CP?'),
        ),
        migrations.AlterField(
            model_name='channelpartner',
            name='monthly_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly revenue target', max_digits=15),
        ),
        migrations.AlterField(
            model_name='channelpartner',
            name='onboarded_by',
            field=models.ForeignKey(blank=True, help_text='Admin/User who onboarded this CP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarded_cps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channelpartner',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN Card Number', max_length=10),
        ),
        migrations.AlterField(
            model_name='channelpartner',
            name='parent_cp',
            field=models.ForeignKey(blank=True, help_text='Parent Channel Partner (for sub-CP structure)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_cps', to='partners.channelpartner'),
        ),
        migrations.AlterField(
            model_name='channelpartner',
            name='quarterly_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quarterly revenue target', max_digits=15),
        ),
        migrations.AlterField(
            model_name='channelpartner',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When was CP verified?', null=True),
        ),
        migrations.AlterField(
            model_name='channelpartner',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified this CP', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='channelpartner',
            name='yearly_target',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Yearly revenue target', max_digits=15),
        ),
        migrations.AlterField(
            model_name='cpcommissionrule',
            name='property',
            field=models.ForeignKey(blank=True, help_text='Specific property (null = applies to all properties)', null=True, on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
        migrations.AlterField(
            model_name='cpcustomerrelation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this relationship currently active?'),
        ),
        migrations.AlterField(
            model_name='cpcustomerrelation',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Referral code used by customer', max_length=50),
        ),
        migrations.AlterField(
            model_name='cpcustomerrelation',
            name='referral_date',
            field=models.DateTimeField(auto_now_add=True, help_text='When customer was referred'),
        ),
        migrations.AlterUniqueTogether(
            name='cpcommissionrule',
            unique_together={('cp', 'commission_rule', 'property')},
        ),
        migrations.AddIndex(
            model_name='channelpartner',
            index=models.Index(fields=['is_verified'], name='channel_par_is_veri_2c1cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='channelpartner',
            index=models.Index(fields=['onboarding_status'], name='channel_par_onboard_c6a2bd_idx'),
        ),
        migrations.AddIndex(
            model_name='channelpartner',
            index=models.Index(fields=['partner_tier'], name='channel_par_partner_f62bae_idx'),
        ),
        migrations.AddIndex(
            model_name='channelpartner',
            index=models.Index(fields=['agent_type'], name='channel_par_agent_t_c78b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionrule',
            index=models.Index(fields=['is_default'], name='commission__is_defa_e1f21b_idx'),
        ),
        migrations.AddIndex(
            model_name='cpcommissionrule',
            index=models.Index(fields=['cp'], name='cp_commissi_cp_id_0301b2_idx'),
        ),
        migrations.AddIndex(
            model_name='cpcommissionrule',
            index=models.Index(fields=['property'], name='cp_commissi_propert_ce9795_idx'),
        ),
        migrations.AddIndex(
            model_name='cpcustomerrelation',
            index=models.Index(fields=['expiry_date'], name='cp_customer_expiry__e49635_idx'),
        ),
        migrations.AddIndex(
            model_name='cpcustomerrelation',
            index=models.Index(fields=['is_expired'], name='cp_customer_is_expi_89a08e_idx'),
        ),
        migrations.AddField(
            model_name='cpdocument',
            name='cp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='partners.channelpartner'),
        ),
        migrations.AddField(
            model_name='cpdocument',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cpdocument',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Admin who verified this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cp_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cpinvite',
            name='cp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='partners.channelpartner'),
        ),
        migrations.AddField(
            model_name='cpinvite',
            name='used_by',
            field=models.ForeignKey(blank=True, help_text='User who used this invite', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cplead',
            name='converted_customer',
            field=models.ForeignKey(blank=True, help_text='User account created when lead converted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_from_lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cplead',
            name='cp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='partners.channelpartner'),
        ),
        migrations.AddField(
            model_name='cplead',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cplead',
            name='interested_property',
            field=models.ForeignKey(blank=True, help_text='Which property is lead interested in?', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cp_leads', to='properties.property'),
        ),
        migrations.AddField(
            model_name='cppropertyauthorization',
            name='authorized_by',
            field=models.ForeignKey(blank=True, help_text='Admin who authorized this', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_cp_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cppropertyauthorization',
            name='cp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_authorizations', to='partners.channelpartner'),
        ),
        migrations.AddField(
            model_name='cppropertyauthorization',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cp_authorizations', to='properties.property'),
        ),
        migrations.AddIndex(
            model_name='cpdocument',
            index=models.Index(fields=['cp', 'document_type'], name='cp_document_cp_id_b085c9_idx'),
        ),
        migrations.AddIndex(
            model_name='cpdocument',
            index=models.Index(fields=['status'], name='cp_document_status_cc921e_idx'),
        ),
        migrations.AddIndex(
            model_name='cpdocument',
            index=models.Index(fields=['document_type'], name='cp_document_documen_891a0d_idx'),
        ),
        migrations.AddIndex(
            model_name='cpinvite',
            index=models.Index(fields=['cp', 'is_used'], name='cp_invites_cp_id_d336c6_idx'),
        ),
        migrations.AddIndex(
            model_name='cpinvite',
            index=models.Index(fields=['invite_code'], name='cp_invites_invite__43706c_idx'),
        ),
        migrations.AddIndex(
            model_name='cpinvite',
            index=models.Index(fields=['phone'], name='cp_invites_phone_d2e244_idx'),
        ),
        migrations.AddIndex(
            model_name='cpinvite',
            index=models.Index(fields=['is_expired'], name='cp_invites_is_expi_af1a67_idx'),
        ),
        migrations.AddIndex(
            model_name='cpinvite',
            index=models.Index(fields=['expiry_date'], name='cp_invites_expiry__f6ba35_idx'),
        ),
        migrations.AddIndex(
            model_name='cplead',
            index=models.Index(fields=['cp', 'lead_status'], name='cp_leads_cp_id_947887_idx'),
        ),
        migrations.AddIndex(
            model_name='cplead',
            index=models.Index(fields=['phone'], name='cp_leads_phone_d06495_idx'),
        ),
        migrations.AddIndex(
            model_name='cplead',
            index=models.Index(fields=['lead_status'], name='cp_leads_lead_st_168e95_idx'),
        ),
        migrations.AddIndex(
            model_name='cplead',
            index=models.Index(fields=['converted_customer'], name='cp_leads_convert_5fc438_idx'),
        ),
        migrations.AddIndex(
            model_name='cplead',
            index=models.Index(fields=['next_follow_up_date'], name='cp_leads_next_fo_1a6e10_idx'),
        ),
        migrations.AddIndex(
            model_name='cppropertyauthorization',
            index=models.Index(fields=['cp', 'is_authorized'], name='cp_property_cp_id_e99756_idx'),
        ),
        migrations.AddIndex(
            model_name='cppropertyauthorization',
            index=models.Index(fields=['property', 'is_authorized'], name='cp_property_propert_09b653_idx'),
        ),
        migrations.AddIndex(
            model_name='cppropertyauthorization',
            index=models.Index(fields=['approval_status'], name='cp_property_approva_9c8caa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cppropertyauthorization',
            unique_together={('cp', 'property')},
        ),
    ]
