# Generated by Django 5.2.8 on 2025-12-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_cpdocument_cpinvite_cplead_cppropertyauthorization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpinvite',
            name='is_permanent',
            field=models.BooleanField(default=False, help_text='Is this a permanent/reusable invite? (Multiple users can use it)'),
        ),
    ]
