"""
Django settings for aum_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2n))0f$s)74f&ckwady!i968e8qdfyoj+y7lat%x9bj#e8*hq*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',  # ← ADD THIS

    # Your apps
    'accounts.apps.AccountsConfig',  # Important: Use AccountsConfig for signals
    'partners',
    'properties',
    'investments',
    'commissions',
    'compliance',
    'workflows',
]


AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS Settings (for React frontend)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React dev server
    "http://localhost:5173",  # Vite dev server (if using Vite)
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'aum_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aum_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Cache (for OTP storage - using simple in-memory cache for now)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

OTP_EXPIRY_TIME = 300
OTP_LENGTH = 6

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ========================================
# ROUTE MOBILE SMS GATEWAY CONFIGURATION
# ========================================

# Route Mobile Credentials (From working config)
ROUTE_MOBILE_USERNAME = 'VCSMST'
ROUTE_MOBILE_PASSWORD = '[PdjH9-6'
ROUTE_MOBILE_SERVER = 'https://sms6.rmlconnect.net:8443'

# DLT Configuration
ROUTE_MOBILE_ENTITY_ID = '1201173433382664591'

# Template IDs
ROUTE_MOBILE_TEMPLATE_ID = '1207175862143571237'  # For OTP
ROUTE_MOBILE_TEMPLATE_ID_FORGOT = '1207173989148090531'  # For forgot password

# Sender ID
ROUTE_MOBILE_SENDER_ID = 'VBCONN'

# Test Mode (Set to False for production)
ROUTE_MOBILE_TEST_MODE = True  # Set to True for testing without sending real SMS

# ========================================
# LOGGING CONFIGURATION
# ========================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'accounts': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# ========================================
# SUREPASS KYC API CONFIGURATION
# ========================================

# Surepass API credentials
SUREPASS_API_TOKEN = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc2NDMyMzcyMiwianRpIjoiZWRiYTk5ODEtMzdlOC00NzM2LWE0MjAtZGI2MWM2NzIwNmE2IiwidHlwZSI6ImFjY2VzcyIsImlkZW50aXR5IjoiZGV2LnVzZXJuYW1lXzJxaW5lY3JwM3NhczNpZTNxb2ZtZG1uam9scEBzdXJlcGFzcy5pbyIsIm5iZiI6MTc2NDMyMzcyMiwiZXhwIjoxNzY0OTI4NTIyLCJlbWFpbCI6InVzZXJuYW1lXzJxaW5lY3JwM3NhczNpZTNxb2ZtZG1uam9scEBzdXJlcGFzcy5pbyIsInRlbmFudF9pZCI6Im1haW4iLCJ1c2VyX2NsYWltcyI6eyJzY29wZXMiOlsidXNlciJdfX0.y6SUpgwjfSk3snqx_PrUqfi4JmmdjLV5c0b6H1qEZtE'
# Get from Surepass dashboard


# SUREPASS_BASE_URL = 'https://kyc-api.surepass.io'  # Production URL
SUREPASS_BASE_URL = 'https://sandbox.surepass.io'  # Production URL

# Test Mode - Set to True for mock responses (no API calls, no charges)
# Set to False when you have real credentials and want to use production APIs
SUREPASS_TEST_MODE = True  

# ========================================
# MEDIA FILES CONFIGURATION
# ========================================
# For KYC document uploads

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')