"""
Django settings for aum_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os


# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-2n))0f$s)74f&ckwady!i968e8qdfyoj+y7lat%x9bj#e8*hq*'

SECRET_KEY = env('SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', default=False)

#ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.29.63']
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',

    # Your apps
    'accounts.apps.AccountsConfig',  # Important: Use AccountsConfig for signals
    'partners',
    'properties',
    'investments',
    'commissions',
    'compliance',
    'workflows',
    'documents',
]


AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# CORS Settings (for React frontend)
# CORS Settings (for React frontend)
# Prefer env override; include dev + prod origins by default
CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=[
    "https://app.assetkart.com",
    "http://app.assetkart.com",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
])

CORS_ALLOW_CREDENTIALS = True

# Only allow all origins in explicit local dev (avoid in production)
# Set CORS_ALLOW_ALL_ORIGINS=True in .env only for local development
CORS_ALLOW_ALL_ORIGINS = env.bool('CORS_ALLOW_ALL_ORIGINS', default=False)

ROOT_URLCONF = 'aum_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'aum_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

# Use PostgreSQL if DATABASE_URL is set, otherwise use SQLite
if env('DATABASE_URL', default=None):
    DATABASES = {
        'default': dj_database_url.config(
            default=env('DATABASE_URL'),
            conn_max_age=600
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Cache (for OTP storage - using simple in-memory cache for now)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

OTP_EXPIRY_TIME = 300
OTP_LENGTH = 6

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ========================================
# ROUTE MOBILE SMS GATEWAY CONFIGURATION
# ========================================

# Route Mobile Credentials (From working config)
# ========================================
# ROUTE MOBILE SMS GATEWAY CONFIGURATION
# ========================================

# ROUTE_MOBILE_SMS_CONFIG = {
#     "USERNAME": "VCSMST",
#     "PASSWORD": "[PdjH9-6",
#     "TYPE": 5,  # ISO-8859-1 encoding
#     "DLR": 1,   # Enable delivery report
#     "SOURCE": "VBCONN",
#     "ENTITY_ID": "1201173433382664591",
#     "TEMPLATE_ID": "1207175862143571237",
#     "BASE_URL": "https://sms6.rmlconnect.net:8443/bulksms/bulksms",
# }



# Test Mode (Set to False for real SMS)
# ROUTE_MOBILE_TEST_MODE = True


# Route Mobile Configuration
ROUTE_MOBILE_SMS_CONFIG = {
    "USERNAME": env('ROUTE_MOBILE_USERNAME'),
    "PASSWORD": env('ROUTE_MOBILE_PASSWORD'),
    "TYPE": 5,
    "DLR": 1,
    "SOURCE": env('ROUTE_MOBILE_SOURCE'),
    "ENTITY_ID": env('ROUTE_MOBILE_ENTITY_ID'),
    "TEMPLATE_ID": env('ROUTE_MOBILE_TEMPLATE_ID'),
    "BASE_URL": "https://sms6.rmlconnect.net:8443/bulksms/bulksms",
}

ROUTE_MOBILE_TEST_MODE = env.bool('ROUTE_MOBILE_TEST_MODE', default=False)


# ========================================
# LOGGING CONFIGURATION
# ========================================

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'accounts': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
   'investments': {  # ADD THIS
        'handlers': ['console'],
        'level': 'INFO',
        'propagate': False,
    },
}


# ========================================
# SUREPASS KYC API CONFIGURATION
# ========================================

# Surepass Configuration
SUREPASS_ENV = env('SUREPASS_ENV', default='').strip().lower()
_surepass_legacy_token = env('SUREPASS_API_TOKEN', default='')
_surepass_legacy_base_url = env(
    'SUREPASS_BASE_URL',
    default='https://sandbox.surepass.io',
).rstrip('/')

if SUREPASS_ENV in ('prod', 'production'):
    SUREPASS_API_TOKEN = env('SUREPASS_PROD_API_TOKEN', default=_surepass_legacy_token)
    SUREPASS_BASE_URL = env(
        'SUREPASS_PROD_BASE_URL',
        default=_surepass_legacy_base_url,
    ).rstrip('/')
elif SUREPASS_ENV == 'sandbox':
    SUREPASS_API_TOKEN = env('SUREPASS_SANDBOX_API_TOKEN', default=_surepass_legacy_token)
    SUREPASS_BASE_URL = env(
        'SUREPASS_SANDBOX_BASE_URL',
        default=_surepass_legacy_base_url,
    ).rstrip('/')
else:
    SUREPASS_API_TOKEN = _surepass_legacy_token
    SUREPASS_BASE_URL = _surepass_legacy_base_url

SUREPASS_TEST_MODE = env.bool('SUREPASS_TEST_MODE', default=True)
SUREPASS_BANK_TEST_MODE = env.bool('SUREPASS_BANK_TEST_MODE', default=False)


# ========================================
# MEDIA FILES CONFIGURATION
# ========================================
# For KYC document uploads

import os

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



FRONTEND_BASE_URL = env('FRONTEND_BASE_URL', default='http://localhost:5173')
# ========================================
CP_CUSTOMER_RELATION_VALIDITY_DAYS = env.int('CP_RELATION_VALIDITY_DAYS', default=90)
CP_INVITE_VALIDITY_DAYS = env.int('CP_INVITE_VALIDITY_DAYS', default=30)



#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = 587
#EMAIL_USE_TLS = True
#EMAIL_HOST_USER = 'vasisayed09421@gmail.com'
#EMAIL_HOST_PASSWORD = 'zfwlrmkvnawjhiak'

#DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.hostinger.com'
EMAIL_PORT = 465

EMAIL_USE_SSL = True
EMAIL_USE_TLS = False     # must be False — SSL only

EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='invest@assetkart.com')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
ADMIN_NOTIFICATION_EMAIL = env('ADMIN_NOTIFICATION_EMAIL', default=EMAIL_HOST_USER)
