# Generated by Django 5.2.8 on 2025-11-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_indian_user_profile_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='LEGACY FIELD - Synced from compliance.KYC.status', max_length=20),
        ),
    ]
