# Generated by Django 5.2.8 on 2025-12-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_admin_user_is_suspended_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cp_status',
            field=models.CharField(blank=True, choices=[('not_applied', 'Not Applied'), ('pending', 'Pending Review'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_applied', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active_cp',
            field=models.BooleanField(default=False, help_text='Active CP with access'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_cp',
            field=models.BooleanField(default=False, help_text='Is Channel Partner'),
        ),
    ]
