# Generated by Django 5.2.8 on 2025-12-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_cp_status_user_is_active_cp_user_is_cp'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(db_index=True, help_text='Normalized phone number with country code', max_length=15)),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='OTP expiry time (typically 5 minutes)')),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Has this OTP been successfully verified?')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When was OTP verified', null=True)),
                ('attempt_count', models.IntegerField(default=0, help_text='Number of failed verification attempts')),
                ('max_attempts', models.IntegerField(default=5, help_text='Maximum allowed attempts before blocking')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this OTP still active? (invalidated when new OTP sent)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address that requested OTP', null=True)),
                ('sms_sent', models.BooleanField(default=False, help_text='Was SMS successfully sent?')),
                ('sms_message_id', models.CharField(blank=True, help_text='Route Mobile message ID for tracking', max_length=100)),
                ('purpose', models.CharField(choices=[('signup', 'Signup'), ('login', 'Login'), ('reset_password', 'Reset Password')], default='login', help_text='Why was OTP requested?', max_length=20)),
            ],
            options={
                'db_table': 'otp_verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone', 'is_active', 'expires_at'], name='otp_verific_phone_0581ac_idx'), models.Index(fields=['phone', 'is_verified'], name='otp_verific_phone_a31b9c_idx'), models.Index(fields=['created_at'], name='otp_verific_created_6264a2_idx'), models.Index(fields=['-expires_at'], name='otp_verific_expires_f7e06d_idx')],
            },
        ),
    ]
