# Generated by Django 5.2.8 on 2025-11-26 10:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('land', 'Land'), ('mixed', 'Mixed Use')], max_length=20)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('total_area', models.DecimalField(decimal_places=2, help_text='in sq ft', max_digits=10)),
                ('total_units', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('available_units', models.IntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('minimum_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('maximum_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('funded_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('expected_return_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('expected_return_period', models.IntegerField(blank=True, help_text='in months', null=True)),
                ('lock_in_period', models.IntegerField(default=0, help_text='in months')),
                ('project_duration', models.IntegerField(help_text='in months')),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('funding_start_date', models.DateField(blank=True, null=True)),
                ('funding_end_date', models.DateField(blank=True, null=True)),
                ('possession_date', models.DateField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='properties/featured/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('live', 'Live'), ('funding', 'Funding'), ('funded', 'Fully Funded'), ('under_construction', 'Under Construction'), ('completed', 'Completed'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('highlights', models.JSONField(blank=True, default=list)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_properties', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developed_properties', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='accounts.organization')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('prospectus', 'Prospectus'), ('legal', 'Legal Document'), ('approval', 'Government Approval'), ('plan', 'Floor Plan'), ('brochure', 'Brochure'), ('agreement', 'Agreement'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='properties/documents/')),
                ('is_public', models.BooleanField(default=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_documents',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='properties/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'db_table': 'property_images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_number', models.CharField(max_length=50)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('area', models.DecimalField(decimal_places=2, help_text='in sq ft', max_digits=10)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('reserved_at', models.DateTimeField(blank=True, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.property')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_units', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_units',
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['organization', 'status'], name='properties_organiz_dc073f_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['slug'], name='properties_slug_e22d01_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['developer'], name='properties_develop_cae739_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'state'], name='properties_city_d76a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyunit',
            index=models.Index(fields=['property', 'status'], name='property_un_propert_a53fbc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='propertyunit',
            unique_together={('property', 'unit_number')},
        ),
    ]
