# Generated by Django 5.2.8 on 2025-11-28 06:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='builder_name',
            field=models.CharField(default=1, help_text='Builder/Developer company name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='gross_yield',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Gross Yield %', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='is_presale',
            field=models.BooleanField(default=False, help_text='Pre-launch/Early bird sale'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_public_sale',
            field=models.BooleanField(default=True, help_text='Available for public investment'),
        ),
        migrations.AddField(
            model_name='property',
            name='locality',
            field=models.CharField(blank=True, help_text='Area/Locality name', max_length=200),
        ),
        migrations.AddField(
            model_name='property',
            name='potential_gain',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Potential Gain %', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='expected_return_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target IRR %', max_digits=5, null=True),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_public_sale', 'is_presale'], name='properties_is_publ_9892f7_idx'),
        ),
    ]
