# Generated by Django 5.2.8 on 2025-11-28 10:44

import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_builder_name_property_gross_yield_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydocument',
            name='file',
            field=models.FileField(upload_to=properties.models.property_document_upload_path),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.ImageField(upload_to=properties.models.property_image_upload_path),
        ),
    ]
