# Generated by Django 5.2.8 on 2025-11-28 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propertydocument_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_count', models.IntegerField(default=1)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('converted', 'Converted to Investment'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('contacted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacted_interests', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='properties.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'property_interests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['property', 'status'], name='property_in_propert_feebc6_idx'), models.Index(fields=['user'], name='property_in_user_id_b915c2_idx')],
                'unique_together': {('property', 'user')},
            },
        ),
    ]
