# Generated by Django 5.2.8 on 2025-12-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('equity', 'Equity'), ('debt_income', 'Debt Income'), ('hybrid', 'Hybrid')], max_length=20),
        ),
    ]
