# Generated by Django 5.2.8 on 2025-12-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expected_return_period',
            field=models.CharField(blank=True, help_text='in months', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='potential_gain',
            field=models.CharField(blank=True, help_text='Potential Gain %', max_length=10, null=True),
        ),
    ]
