# Generated by Django 5.2.8 on 2025-12-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_expected_return_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expected_return_percentage',
            field=models.CharField(blank=True, help_text='Target IRR %', max_length=10, null=True),
        ),
    ]
