# Generated by Django 5.2.8 on 2025-12-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_alter_property_expected_return_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='expected_return_percentage',
            field=models.CharField(blank=True, help_text='Target IRR %', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='expected_return_period',
            field=models.CharField(blank=True, help_text='in months', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='potential_gain',
            field=models.CharField(blank=True, help_text='Potential Gain %', max_length=30, null=True),
        ),
    ]
