# Generated by Django 5.2.8 on 2026-03-06 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('properties', '0008_alter_property_expected_return_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_documents', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('COMMON', 'Common'), ('INDIVIDUAL', 'Individual'), ('PROPERTY', 'Property')], default='COMMON', max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='individual_docs', to=settings.AUTH_USER_MODEL),
        ),
    ]
