# Generated by Django 4.2.29 on 2026-03-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_esign_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentesignrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
