# Generated by Django 5.2.8 on 2026-03-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documentesignrequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentesignrequest',
            name='identity_check_status',
            field=models.CharField(choices=[('not_checked', 'Not Checked'), ('verified', 'Verified'), ('unverified', 'Unverified'), ('mismatch', 'Mismatch')], default='not_checked', help_text='Result of comparing provider signer identity against KYC/profile', max_length=20),
        ),
        migrations.AddField(
            model_name='documentesignrequest',
            name='identity_mismatch_reason',
            field=models.TextField(blank=True, help_text='Explanation when identity_check_status is mismatch or unverified'),
        ),
        migrations.AddField(
            model_name='documentesignrequest',
            name='signer_name_returned',
            field=models.CharField(blank=True, help_text='Signer name returned by the eSign provider (if any)', max_length=255),
        ),
        migrations.AlterField(
            model_name='documentesignrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('signed', 'Signed'), ('failed', 'Failed'), ('expired', 'Expired'), ('needs_review', 'Needs Review'), ('identity_mismatch', 'Identity Mismatch')], default='pending', max_length=20),
        ),
    ]
