# Generated by Django 5.2.8 on 2025-11-27 09:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commission_id', models.CharField(max_length=100, unique=True)),
                ('commission_type', models.CharField(choices=[('direct', 'Direct Commission'), ('override', 'Override Commission'), ('recurring', 'Recurring Commission'), ('bonus', 'Bonus')], max_length=20)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tds_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('processing', 'Processing'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commissions', to=settings.AUTH_USER_MODEL)),
                ('commission_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='partners.commissionrule')),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='partners.channelpartner')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='investments.investment')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='investments.transaction')),
            ],
            options={
                'db_table': 'commissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payout_id', models.CharField(max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tds_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_mode', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('commissions', models.ManyToManyField(related_name='payouts', to='commissions.commission')),
                ('cp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payouts', to='partners.channelpartner')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_commission_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commission_payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['commission_id'], name='commissions_commiss_b58155_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['cp', 'status'], name='commissions_cp_id_16301f_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['investment'], name='commissions_investm_8bf3f9_idx'),
        ),
        migrations.AddIndex(
            model_name='commission',
            index=models.Index(fields=['status', 'created_at'], name='commissions_status_eec601_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionpayout',
            index=models.Index(fields=['payout_id'], name='commission__payout__f3bb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='commissionpayout',
            index=models.Index(fields=['cp', 'status'], name='commission__cp_id_66d982_idx'),
        ),
    ]
