# Generated by Django 5.2.8 on 2025-12-05 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        ('partners', '0002_cpdocument_cpinvite_cplead_cppropertyauthorization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='is_override',
            field=models.BooleanField(default=False, help_text='Is this an override commission for parent CP?'),
        ),
        migrations.AddField(
            model_name='commission',
            name='paid_by',
            field=models.ForeignKey(blank=True, help_text='User who processed the payout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='parent_commission',
            field=models.ForeignKey(blank=True, help_text='Base commission (if this is override)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_commissions', to='commissions.commission'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='cp',
            field=models.ForeignKey(help_text='Channel Partner receiving commission', on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='partners.channelpartner'),
        ),
    ]
